### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by PandasMagic** [PandasMagic/Comp-Client#1]
- [ ] Client settings menu
- [ ] Client Keybinds (Fix to the buggy in game ones)
- [ ] Loading menu (For aesthetics) 
- [ ] Custom scopes
- [ ] Redo PClient mods but (maybe) better
